sodu: required
services:
  - docker

brfore_install:
  - docker build -t pad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pad/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-339712740765"
  bucket_path: "frontend"
  on:
    branch: master